name: PHPUnit

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 6

    steps:
    - name: Checkout
      uses: actions/checkout@v3

      # https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md#cache-backend-api
      #OPTIONAL CACHE SETUP -->
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-
      #OPTIONAL CACHE SETUP <--

    - name: Docker build
      run: docker-compose build
      timeout-minutes: 3

    - # OPTIONAL CACHE SETUP -->
      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      name: Move cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache
      # OPTIONAL CACHE SETUP <--

    - name: Docker boot
      run: docker-compose up --no-build --no-color -d
      timeout-minutes: 2

    - name: Docker eficode/wait-for
      run: wget -qO- https://raw.githubusercontent.com/eficode/wait-for/v2.2.3/wait-for | sh -s -- 127.0.0.1:3306 -- echo success
      timeout-minutes: 2

    - name: Docker install dependencies
      run: docker-compose exec -T app composer install --dev

    - name: Sleep
      run: sleep 5

      # Docs: https://phpunit.readthedocs.io/en/9.5/
    - name: Docker run PHPUnit
      run: docker-compose exec -T app composer app-phpunit-coverage

      # Docs: https://github.com/marketplace/actions/phpunit-coverage-badge
    - name: Generate PHPUnit coverage badge
      uses: timkrase/phpunit-coverage-badge@v1.2.0
      with:
        coverage_badge_path: 'doc/phpunit-coverage-badge.svg'
        push_badge: true
        report: test/clover.xml
        repo_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Shutdown
      run: docker-compose down
      timeout-minutes: 1
