name: PHPUnit

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci]')"

    timeout-minutes: 6

    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

      # OPTIONAL
      # https://depot.dev/blog/docker-layer-caching-in-github-actions
      # pre-build the build/Dockerfile with caching
    - uses: docker/setup-buildx-action@v1
    - uses: docker/build-push-action@v2
      with:
        context: ./build
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Docker build
      run: docker-compose build
      timeout-minutes: 3

    - name: Docker boot
      run: docker-compose up --no-build --no-color -d
      timeout-minutes: 2

    - name: Docker eficode/wait-for
      run: wget -qO- https://raw.githubusercontent.com/eficode/wait-for/v2.2.3/wait-for | sh -s -- 127.0.0.1:3306 -- echo success
      timeout-minutes: 2

    - name: Docker install dependencies
      run: docker-compose exec -T app composer install --dev

    - name: Sleep
      run: sleep 5

      # Docs: https://phpunit.readthedocs.io/en/9.5/
    - name: Docker run PHPUnit
      run: docker-compose exec -T app composer app-phpunit-coverage

    - name: Show github auth status
      run: gh auth status

      # Docs: https://github.com/marketplace/actions/phpunit-coverage-badge
    - name: Generate PHPUnit coverage badge
      uses: timkrase/phpunit-coverage-badge@v1.2.0
      with:
        coverage_badge_path: 'doc/phpunit-coverage-badge.svg'
        push_badge: true
        report: test/clover.xml
        repo_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Shutdown
      run: docker-compose down
      timeout-minutes: 1
