# This file is part of the sshilko/php-sql-mydb package.
#
# (c) Sergei Shilko <contact@sshilko.com>
#
# MIT License
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
# @license https://opensource.org/licenses/mit-license.php MIT
name: 7.4 Phan

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip-github-actions')"
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: PHP setup
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: simplexml,dom,xml,intl,ast,mysql,xdebug
          coverage: xdebug

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}-composer-dev

      - name: PHP Version
        run: php --version

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --optimize-autoloader

        # Docs: https://github.com/phan/phan
      - name: Run Phan github.com/phan/phan
        env:
          PHAN_ALLOW_XDEBUG: 1
          PHAN_DISABLE_XDEBUG_WARN: 1
        run: composer app-phan
