# This file is part of the sshilko/php-sql-mydb package.
#
# (c) Sergei Shilko <contact@sshilko.com>
#
# MIT License
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
# @license https://opensource.org/licenses/mit-license.php MIT
name: 7.4 Phan

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: PHP setup
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: simplexml,dom,xml,intl,ast,mysql,xdebug
          coverage: xdebug

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}-composer-dev

      - name: PHP Version
        run: php --version

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --optimize-autoloader

        # Docs: https://github.com/phan/phan
      - name: Run Phan github.com/phan/phan
        run: composer app-phan > build/tmp/phan.txt 2>&1

        # https://github.com/actions/upload-artifact
      - name: Upload Phan artifacts
        uses: actions/upload-artifact@v3
        with:
            name: phan-output
            path: |
                build/tmp/phan.html
                build/tmp/phan.txt
            retention-days: 1
  pages:
      needs: build
      runs-on: ubuntu-latest
      timeout-minutes: 2
      permissions: write-all
      steps:
          # https://github.com/actions/checkout
          - name: Checkout pages branch
            uses: actions/checkout@v3
            with:
                ref: pages

              #https://github.com/marketplace/actions/download-a-build-artifact
          - name: Download all Phan artifacts
            uses: actions/download-artifact@v3
            with:
                name: phan-output
                path: php/phan

          - uses: nick-fields/retry@v2
            name: Commit php/phan
            continue-on-error: true
            with:
                timeout_seconds: 20
                max_attempts: 3
                retry_on: error
                command: |
                    git status
                    git config user.name github-actions
                    git config user.email github-actions@github.com
                    git pull
                    git add php/phan/phan.txt
                    git add php/phan/phan.html
                    git commit -m "generated phan docs from revision ${GITHUB_SHA::7}"
                    git push
