name: PHPMd

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci]')"
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: PHP setup
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: simplexml,dom,xml,intl,ast,mysql,xdebug
          coverage: xdebug

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: PHP Version
        run: php --version

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --optimize-autoloader

        # Docs: https://github.com/psalm/shepherd
      - name: Run psalm suite and send shepherd stats
        run: composer app-phpmd
