name: 8.1 PHPUnit

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip-github-actions')"
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      platforms: linux/amd64

    - name: Cache Docker php-image
      id: docker-php-image-cache
      uses: actions/cache@v3
      with:
        path: /tmp/docker-save
        key: ${{ runner.os }}-docker-php-build-save-${{ hashFiles('build/Dockerfile.php', 'build/Dockerfile81') }}
    - run: docker load -i /tmp/docker-save/snapshot.tar || true
      if: steps.docker-php-image-cache.outputs.cache-hit == 'true'
    - run: docker build build/Dockerfile -t php-image --cache-from=php-image-cache
      env:
        DOCKER_BUILDKIT: '1'
        COMPOSE_DOCKER_CLI_BUILD: '1'
    - run: docker tag php-image php-image-cache && mkdir -p /tmp/docker-save && docker save php-image-cache -o /tmp/docker-save/snapshot.tar && ls -lh /tmp/docker-save || true
      if: always() && steps.docker-php-image-cache.outputs.cache-hit != 'true'

    - name: Docker boot
      env:
        SERVICES_NAME: "app81 mysql mysql80"
      run: docker-compose up -d $SERVICES_NAME
      timeout-minutes: 4

    - name: Docker eficode/wait-for MySQL 5.7
      run: wget -qO- https://raw.githubusercontent.com/eficode/wait-for/v2.2.3/wait-for | sh -s -- 127.0.0.1:3306 -- echo success
      timeout-minutes: 1

    - name: Docker eficode/wait-for MySQL 8.0
      run: wget -qO- https://raw.githubusercontent.com/eficode/wait-for/v2.2.3/wait-for | sh -s -- 127.0.0.1:4306 -- echo success
      timeout-minutes: 1

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}-composer-dev

    - name: Docker install dependencies
      run: docker-compose exec -T app81 composer install

    - name: Sleep
      run: sleep 10

      # Docs: https://phpunit.readthedocs.io/en/9.5/
    - name: Docker run PHPUnit
      run: docker-compose exec -T app81 composer app-phpunit
