name: 7.4 PHPUnit

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build-containers:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip-github-actions')"
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker php-image
        id: docker-php-image-cache
        uses: actions/cache@v3
        with:
          path: /tmp/docker-save
          key: ${{ runner.os }}-docker-php-build-save-${{ hashFiles('**/Dockerfile.php.common', '**/Dockerfile.php74') }}

      - name: Load cached Docker image
        run: docker load -i /tmp/docker-save/snapshot.tar || true
        if: steps.docker-php-image-cache.outputs.cache-hit == 'true'

      - name: Build Docker image
        run: ls -l && docker build -f build/Dockerfile.php74 -t app/php-image --cache-from=app/php-image-cache ./build
        if: steps.docker-php-image-cache.outputs.cache-hit != 'true'
        env:
          DOCKER_BUILDKIT: '1'
          COMPOSE_DOCKER_CLI_BUILD: '1'

      - name: Tag Docker image
        run: docker tag app/php-image app/php-image-cache && mkdir -p /tmp/docker-save && docker save app/php-image-cache -o /tmp/docker-save/snapshot.tar && ls -lh /tmp/docker-save || true
        if: always() && steps.docker-php-image-cache.outputs.cache-hit != 'true'

  build:
    needs: build-containers
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip-github-actions')"
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Load cached app docker image
      id: docker-php-image-cache
      uses: actions/cache@v3
      with:
        path: /tmp/docker-save
        key: ${{ runner.os }}-docker-php-build-save-${{ hashFiles('**/Dockerfile.php.common', '**/Dockerfile.php74') }}
    - name: Load cached Docker image
      run: docker load -i /tmp/docker-save/snapshot.tar && docker tag app/php-image-cache app/php

    - name: Docker boot
      env:
        DOCKER_BUILDKIT: '1'
        COMPOSE_DOCKER_CLI_BUILD: '1'
        SERVICES_NAME: "app.php mysql mysql80"
      run: docker-compose up --no-build -d $SERVICES_NAME
      timeout-minutes: 1

    - name: Wait for all services to become healthy
      run: for CONTAINER_ID in $(docker-compose ps --services); do while [ "\"healthy\"" != "$(docker inspect --format '{{json .State.Health.Status }}' ${CONTAINER_ID})" ];do docker-compose ps && sleep 3; done; done
      timeout-minutes: 1

    - name: Sleep
      run: sleep 4
    - run: docker-compose ps

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}-composer-dev

    - name: Docker install dependencies
      run: docker-compose exec -T app.php composer install

      # Docs: https://phpunit.readthedocs.io/en/9.5/
    - name: Docker run PHPUnit
      run: docker-compose exec -T app.php composer app-phpunit-coverage

      # Docs: https://github.com/marketplace/actions/phpunit-coverage-badge
    - name: Generate PHPUnit coverage badge
      uses: timkrase/phpunit-coverage-badge@v1.2.0
      with:
        coverage_badge_path: 'doc/phpunit-coverage-badge.svg'
        push_badge: false
        report: test/phpunit-coverage/phpunit-clover.xml

      # https://github.com/actions/upload-artifact
    - name: Upload PHPUnit coverage badge as artifact
      uses: actions/upload-artifact@v3
      with:
        name: phpunit-coverage-badge
        path: doc/phpunit-coverage-badge.svg
        retention-days: 1

      # https://github.com/actions/upload-artifact
    - name: Upload PHPUnit Lines coverage badge as artifact
      uses: actions/upload-artifact@v3
      with:
        name: phpunit-coverage-badge-lines
        path: test/phpunit-coverage/phpunit-coverage-badge-lines.svg
        retention-days: 1

      # https://github.com/actions/upload-artifact
    - name: Upload PHPUnit classes coverage badge as artifact
      uses: actions/upload-artifact@v3
      with:
        name: phpunit-coverage-badge-classes
        path: test/phpunit-coverage/phpunit-coverage-badge-classes.svg
        retention-days: 1

      # https://github.com/actions/upload-artifact
    - name: Upload PHPUnit methods coverage badge as artifact
      uses: actions/upload-artifact@v3
      with:
        name: phpunit-coverage-badge-methods
        path: test/phpunit-coverage/phpunit-coverage-badge-methods.svg
        retention-days: 1

    - name: Shutdown docker
      run: docker-compose down
      timeout-minutes: 1

  badges:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 2
    permissions: write-all
    steps:
      # https://github.com/actions/checkout
    - name: Checkout badges branch
      uses: actions/checkout@v3
      with:
        ref: badges

      #https://github.com/marketplace/actions/download-a-build-artifact
    - name: Download all PHPUnit coverage artifacts
      uses: actions/download-artifact@v3.0.1
      with:
        name: phpunit-coverage-badge

      #https://github.com/marketplace/actions/download-a-build-artifact
    - name: Download all PHPUnit coverage artifacts
      uses: actions/download-artifact@v3.0.1
      with:
        name: phpunit-coverage-badge-lines

      #https://github.com/marketplace/actions/download-a-build-artifact
    - name: Download all PHPUnit coverage artifacts
      uses: actions/download-artifact@v3.0.1
      with:
        name: phpunit-coverage-badge-classes

      #https://github.com/marketplace/actions/download-a-build-artifact
    - name: Download all PHPUnit coverage artifacts
      uses: actions/download-artifact@v3.0.1
      with:
        name: phpunit-coverage-badge-methods

    - name: Commit badges
      continue-on-error: true
      run: |
        git status
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add phpunit-coverage-badge.svg
        git add phpunit-coverage-badge-lines.svg
        git add phpunit-coverage-badge-classes.svg
        git add phpunit-coverage-badge-methods.svg
        git commit -m "generated phpunit badges from revision ${GITHUB_SHA::7}"
        git push
