name: 8.0 PHPUnit

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip-github-actions')"
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v3

    - name: Docker boot
      env:
        SERVICES_NAME: "app80 mysql mysql80"
      run: docker-compose up -d $SERVICES_NAME
      timeout-minutes: 3

    - name: Docker eficode/wait-for MySQL 5.7
      env:
        WAIT_FOR_TCP_PORT: 3306
      run: wget -qO- https://raw.githubusercontent.com/eficode/wait-for/v2.2.3/wait-for | sh -s -- 127.0.0.1:$WAIT_FOR_TCP_PORT -- echo success
      timeout-minutes: 1

    - name: Docker eficode/wait-for MySQL 8.0
      env:
        WAIT_FOR_TCP_PORT: 4306
      run: wget -qO- https://raw.githubusercontent.com/eficode/wait-for/v2.2.3/wait-for | sh -s -- 127.0.0.1:$WAIT_FOR_TCP_PORT -- echo success
      timeout-minutes: 1

    - name: Docker install dependencies
      run: docker-compose exec -T app80 composer install --dev

    - name: Sleep
      run: sleep 5

      # Docs: https://phpunit.readthedocs.io/en/9.5/
    - name: Docker run PHPUnit
      run: docker-compose exec -T app80 composer app-phpunit
