name: 7.4 PHPUnit

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip-github-actions')"
    timeout-minutes: 6

    steps:
    - uses: actions/checkout@v3

    - name: Docker boot
      run: docker-compose up -d app mysql
      timeout-minutes: 2

    - name: Docker eficode/wait-for
      run: wget -qO- https://raw.githubusercontent.com/eficode/wait-for/v2.2.3/wait-for | sh -s -- 127.0.0.1:3306 -- echo success
      timeout-minutes: 2

    - name: Docker install dependencies
      run: docker-compose exec -T app composer install --dev

    - name: Sleep
      run: sleep 5

      # Docs: https://phpunit.readthedocs.io/en/9.5/
    - name: Docker run PHPUnit
      run: docker-compose exec -T app composer app-phpunit-coverage

      # Docs: https://github.com/marketplace/actions/phpunit-coverage-badge
    - name: Generate PHPUnit coverage badge
      uses: timkrase/phpunit-coverage-badge@v1.2.0
      with:
        coverage_badge_path: 'doc/phpunit-coverage-badge.svg'
        push_badge: false
        report: test/phpunit-coverage/phpunit-clover.xml

      # https://github.com/actions/upload-artifact
    - name: Upload PHPUnit coverage badge as artifact
      uses: actions/upload-artifact@v3
      with:
        name: phpunit-coverage-badge
        path: doc/phpunit-coverage-badge.svg
        retention-days: 1

      # https://github.com/actions/upload-artifact
    - name: Upload PHPUnit Lines coverage badge as artifact
      uses: actions/upload-artifact@v3
      with:
        name: phpunit-coverage-badge-lines
        path: test/phpunit-coverage/phpunit-coverage-badge-lines.svg
        retention-days: 1

      # https://github.com/actions/upload-artifact
    - name: Upload PHPUnit classes coverage badge as artifact
      uses: actions/upload-artifact@v3
      with:
        name: phpunit-coverage-badge-classes
        path: test/phpunit-coverage/phpunit-coverage-badge-classes.svg
        retention-days: 1

      # https://github.com/actions/upload-artifact
    - name: Upload PHPUnit methods coverage badge as artifact
      uses: actions/upload-artifact@v3
      with:
        name: phpunit-coverage-badge-methods
        path: test/phpunit-coverage/phpunit-coverage-badge-methods.svg
        retention-days: 1

    - name: Shutdown docker
      run: docker-compose down
      timeout-minutes: 1

  badges:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 2
    permissions: write-all
    steps:
      # https://github.com/actions/checkout
    - name: Checkout badges branch
      uses: actions/checkout@v3
      with:
        ref: badges

      #https://github.com/marketplace/actions/download-a-build-artifact
    - name: Download all PHPUnit coverage artifacts
      uses: actions/download-artifact@v3.0.1
      with:
        name: phpunit-coverage-badge

      #https://github.com/marketplace/actions/download-a-build-artifact
    - name: Download all PHPUnit coverage artifacts
      uses: actions/download-artifact@v3.0.1
      with:
        name: phpunit-coverage-badge-lines

      #https://github.com/marketplace/actions/download-a-build-artifact
    - name: Download all PHPUnit coverage artifacts
      uses: actions/download-artifact@v3.0.1
      with:
        name: phpunit-coverage-badge-classes

      #https://github.com/marketplace/actions/download-a-build-artifact
    - name: Download all PHPUnit coverage artifacts
      uses: actions/download-artifact@v3.0.1
      with:
        name: phpunit-coverage-badge-methods

    - name: Commit badges
      continue-on-error: true
      run: |
        git status
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add phpunit-coverage-badge.svg
        git add phpunit-coverage-badge-lines.svg
        git add phpunit-coverage-badge-classes.svg
        git add phpunit-coverage-badge-methods.svg
        git commit -m "generated phpunit badges from revision ${GITHUB_SHA::7}"
        git push
